import os
import json

def load_contract_addresses():
    """
    Load latest addresses from broadcast/addresses.json or broadcast/addresses.base-sepolia.json
    generated by script/AnvilRun.s.sol or BaseSepoliaRun.s.sol
    """
    # Priority: Base Sepolia > Anvil (local)
    paths_to_try = [
        "/app/broadcast/addresses.base-sepolia.json",  # Docker environment, Base Sepolia
        "broadcast/addresses.base-sepolia.json",        # Host environment, Base Sepolia
        "/app/broadcast/addresses.json",                 # Docker environment, Anvil
        "broadcast/addresses.json"                       # Host environment, Anvil
    ]
    
    for path in paths_to_try:
        if os.path.exists(path):
            try:
                with open(path, 'r') as f:
                    config = json.load(f)
                # Config loaded silently
                return config
            except Exception as e:
                print(f"Config: Error loading {path}: {e}. Trying next...", flush=True)
                continue
    
    print(f"Config: No addresses file found. Using defaults.", flush=True)

# Load as global configuration
CONTRACTS = load_contract_addresses()
